BDHelpCommunity/BDHelp/Controllers/ActionController.cs
using BDHelp.Models;
using FInal_Project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BDHelp.Controllers
{
    
    public class ActionController : Controller
    {
        // GET: Action
        public ActionResult Index()
        {                       
            CommunityDbContext context = new CommunityDbContext();
            UserModel model = new UserModel();
            
            ViewBag.Categories = context.Categories.Take(10).ToList();
            ViewBag.User = context.UserModels.Take(5).OrderByDescending(id => id.UserRating).ToList(); ;
            return View(context.UserQuestions.Take(20).OrderByDescending(id => id.QuestionRating).ToList());            
        }
       
        public ActionResult Like(int id)
        {

            //Problem
            if (ModelState.IsValid)
            {
                CommunityDbContext context = new CommunityDbContext();
                //UserQuestion question = new UserQuestion();

                var question = context.UserQuestions.SingleOrDefault(item => item.QuestionId == id);
                int value = Convert.ToInt32(question.QuestionRating) + 1;
                question.QuestionRating = value;
                //context.Entry(question).State = EntityState.Modified;
                context.SaveChanges();
                //onclick="location.href='@Url.Action("Like","Action", new { id=item.QuestionId})'"> @Html.DisplayFor(model => item.QuestionRating)       
                return Redirect(Request.UrlReferrer.AbsolutePath);
            }
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }
        public ActionResult UnLike(int id)
        {
            CommunityDbContext context = new CommunityDbContext();
            var question = context.UserQuestions.SingleOrDefault(item => item.QuestionId == id);
            int value = (Convert.ToInt32(question.Unlike)) + 1;
            question.Unlike = value;
            context.SaveChanges();
            return Redirect(Request.UrlReferrer.AbsolutePath);  
        }
        [HttpGet]
        [ActionName("btnAsk")]
        public ActionResult BtnAsk()
        {
            return Redirect("~/Action/AskQuestion");
        }

        [HttpGet]
        [ActionName("btnSearch")]
        public ActionResult BtnSearch()
        {
            return Redirect("~/Action/Search");
        }

        [HttpGet]
        [ActionName("btnAddCategory")]
        public ActionResult BtnAddCategory()
        {
            return Redirect("~/Action/AddCategory");
        }
        [HttpGet]
       
        public ActionResult AskQuestion()
        {
            CommunityDbContext context = new CommunityDbContext();
            ViewBag.Categories = context.Categories.ToList();
            //ViewBag.Categories=
            return View();

        }
        
        [HttpPost]
        public ActionResult AskQuestion(UserQuestion question)
        {
            question.CategoryId = Convert.ToInt32(Request["Category"]);
            CommunityDbContext context = new CommunityDbContext();
            question.QuestionDate = DateTime.Now;
           // question.Users = Identity.Name;
            context.UserQuestions.Add(question);
            context.SaveChanges();
            return Redirect("Index");

        }

        public ActionResult Search()
        {
            UserQuestion question = new UserQuestion();

            return View();
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        public ActionResult AddCategory(Category cat)
        {
            CommunityDbContext context = new CommunityDbContext();
            context.Categories.Add(cat);
            context.SaveChanges();
            return Redirect("Index");
        }
       public ActionResult ViewProfile(int id)
        {
            CommunityDbContext context = new CommunityDbContext();
            return View(context.UserModels.Where(i=>i.UserId==id).ToList());
        }
        public ActionResult UnansweredQuestion()
        {
            CommunityDbContext context = new CommunityDbContext();
            var answer = context.Answers.Select(i => i.QuestionId).Distinct().ToList();
            var question = from c in context.UserQuestions
                           where !(from a in context.Answers select a.QuestionNo).Contains(c.QuestionId)
                           select c;
            return View(question);
        }
       public ActionResult TopUnliked()
        {
            CommunityDbContext context = new CommunityDbContext();
            var question = context.UserQuestions.Take(20).OrderByDescending(i => i.Unlike);
            return View(question);
        }
        public ActionResult SatisfiedQuestion()
        {
            CommunityDbContext context = new CommunityDbContext();
            var question = context.UserQuestions.Take(50).OrderByDescending(i=>i.QuestionDate).Where(i=>i.IsSatisfied==1);
            return View(question);
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        

    }
}

BDHelpCommunity/BDHelp/Controllers/SearchController.cs
using BDHelp.Models;
using FInal_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BDHelp.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }
        public  PartialViewResult MatchAny(string message)
        {
            CommunityDbContext context = new CommunityDbContext();
            List<UserQuestion> model = context.UserQuestions
                .Where(s => s.QuestionHeader.Contains(message))
                .Select(s => s).ToList();
            return PartialView("_Search", model);
        }
    }
}

BDHelpCommunity/BDHelp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
   
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="BD COMMUNITY">
    <meta name="author" content="ALI AHMED">
    <meta name="keywords" content="BD COMMUNITY">
    <title>BD COMMUNITY</title>
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">
    <link href='https://fonts.googleapis.com/css?family=Allerta' rel='stylesheet' type='text/css'>
    
    

</head>
<body>
    <nav class="navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-menu" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">BD HELP COMMUNITY</a>
            </div>

            <div class="collapse navbar-collapse" id="collapse-menu">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="@Url.Action("Index","Action")">HOME</a></li>
                    <li><a href="@Url.Action("btnAsk","Action")">ASK QUESTION</a></li>                                        
                    <li><a href="@Url.Action("AddCategory","Action")">Add Category</a></li>
                    <li><a href="@Url.Action("AboutUs","Action")">About Us</a></li>
                    @Html.Partial("_LoginPartial")
                   
                </ul>
              
            </div>
        </div>
    </nav>
    <div>
      
       
    </div>
    <br />
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - BD Help Community</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BDHelpCommunity/BDHelp/Views/Shared/_Search.cshtml
@model IEnumerable<FInal_Project.Models.UserQuestion>


<div class="col-md-6 question-post">
    @foreach (var item in Model)
    {
        <div class="question-body">
            <h1><i class="fa fa-hand-o-right"></i>@Html.DisplayFor(model => item.QuestionHeader)</h1>
            <p>by <a href="#">ali ahmed</a></p>
            <p>@Html.DisplayFor(model => item.QuestionDate)</p>
            <p>@Html.DisplayFor(model => item.QuestionText).@Html.ActionLink("ViewQuestion", "../Question/ViewQuestion", new { id = item.QuestionId })</p>


            <div class="button-area">
                <div class="button-like">
                    <button type="button" class="btn" onclick="location.href='@Url.Action("Like","Action",new {id=item.QuestionId })'"> <i class="fa fa-thumbs-up"></i> (@Html.DisplayFor(model => item.QuestionRating)) | Like</button>
                    <button type="button" class="btn" onclick="location.href='@Url.Action("Unlike","Action",new { id = item.QuestionId})'"><i class="fa fa-thumbs-down"></i>(@Html.DisplayFor(model => item.Unlike)) Unlike</button>
                    <button type="button" class="btn"><i class="fa fa-comment"></i> Answers</button>
                    <button type="button" class="btn"><i class="fa fa-comment"></i> Share</button>
                </div>
            </div>
        </div>


    }
    </div>