AuthenticationAndAuthorization/AuthenticationAndAuthorization/Models/Dept.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AuthenticationAndAuthorization.Models
{
    public class Dept
    {
        [Key]
        public int DepartmentId { get; set; }

        public String DepartmentName { get; set; }

        public string Username { get; set; }
        

    }
}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Models/EDBContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace AuthenticationAndAuthorization.Models
{
    public class EDBContext :DbContext
    {

        public DbSet<User> Users { set; get; }

        public DbSet<Dept> Departments { set; get; }

    }
}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AuthenticationAndAuthorization.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }

        public string Username { set; get; }

        public string Password { get; set; }

        public String Role { get; set; }
    }
}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Controllers/DeptsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AuthenticationAndAuthorization.Models;
using AuthenticationAndAuthorization.Security;

namespace AuthenticationAndAuthorization.Controllers
{
    [Authorize(Roles ="admin,customer")]
    public class DeptsController : Controller
    {
        private EDBContext db = new EDBContext();

        // GET: Depts
       
        [Authorize(Roles ="admin,customer")]
        public ActionResult Index()
        {
            return View(db.Departments.Take(50).ToList());
        }

        
        // GET: Depts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dept dept = db.Departments.Find(id);
            if (dept == null)
            {
                return HttpNotFound();
            }
            return View(dept);
        }


        [CustomAuthorize(Roles ="admin")]
        // GET: Depts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Depts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentId,DepartmentName,Username")] Dept dept)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(dept);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dept);
        }

        
        // GET: Depts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dept dept = db.Departments.Find(id);
            if (dept == null)
            {
                return HttpNotFound();
            }
            return View(dept);
        }

        // POST: Depts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentId,DepartmentName,Username")] Dept dept)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dept).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dept);
        }

        
        // GET: Depts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dept dept = db.Departments.Find(id);
            if (dept == null)
            {
                return HttpNotFound();
            }
            return View(dept);
        }

       
        // POST: Depts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dept dept = db.Departments.Find(id);
            db.Departments.Remove(dept);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuthenticationAndAuthorization.Models;
using System.Web.Security;

namespace AuthenticationAndAuthorization.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(User user)
        {

            using(EDBContext db = new EDBContext())
            {
                var count = db.Users.Where(x => x.Username == user.Username && x.Password == user.Password).Count();
                if (count == 1)
                {
                    FormsAuthentication.SetAuthCookie(user.Username, false);//false for remembering
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "Invalid User";
                }
            }
            
            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
        public ActionResult AccessDenied()
        {
            Response.StatusCode = 403;
            return View();
        }

    }

}

/*
           using(EDBContext db = new EDBContext())
           {
                   User user = new User()
                   {
                       Username = "admin",
                       Password="admin",
                       Role="admin"

                   };
                   User user2 = new User()
                   {
                       Username = "customer",
                       Password = "customer",
                       Role = "customer"
                   };
                   db.Users.Add(user);
                   db.Users.Add(user2);

                   Dept dept = new Dept()
                   {
                       DepartmentName="hr",
                       Username="admin"
                   };
                   db.Departments.Add(dept);
               db.SaveChanges();

           }*/

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/Home/AccessDenied.cshtml
@{
    ViewBag.Title = "AccessDenied";
}

<h2 style="color:red">AccessDenied</h2>

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<h3>Home page</h3>

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/Home/Login.cshtml
@model AuthenticationAndAuthorization.Models.User

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm("Login","Home",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @ViewBag.Message
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("View Depts", "Index", "Depts")</li>

                        if (User.IsInRole("admin"))
                        {
                            <li>@Html.ActionLink("Add Depts", "Create", "Depts")</li>
                        }


                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    }
                    
                </ul>

            </div>

        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>